CREATE TABLE visitor_management_schema.society_table
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    regd_no character varying(20) COLLATE pg_catalog."default",
    building_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    building_address text COLLATE pg_catalog."default" NOT NULL,
    total_buildings integer NOT NULL,
    total_flats integer NOT NULL,
    CONSTRAINT society_table_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;


CREATE TABLE visitor_management_schema.user_table
(
    id SERIAL,
    username character varying(30) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    middle_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    isadmin boolean,
    society_id integer NOT NULL DEFAULT 1,
    email character varying COLLATE pg_catalog."default",
    CONSTRAINT user_table_pkey PRIMARY KEY (id),
    CONSTRAINT user_table_society_id_fkey FOREIGN KEY (society_id)
        REFERENCES visitor_management_schema.society_table (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

CREATE TABLE visitor_management_schema.visitor_table
(
    id SERIAL,
    first_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    middle_name character varying(30) COLLATE pg_catalog."default",
    last_name character varying(30) COLLATE pg_catalog."default",
    contact_number character varying(30) COLLATE pg_catalog."default" NOT NULL,
    entry_time timestamp without time zone NOT NULL DEFAULT now(),
    exit_time timestamp without time zone,
    flat_info character varying(30) COLLATE pg_catalog."default" NOT NULL,
    society_id integer,
    staff_id integer,
    visit_reason text COLLATE pg_catalog."default",
    CONSTRAINT visitor_table_pkey PRIMARY KEY (id),
    CONSTRAINT visitor_table_society_id_fkey FOREIGN KEY (society_id)
        REFERENCES visitor_management_schema.society_table (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT visitor_table_staff_id_fkey FOREIGN KEY (staff_id)
        REFERENCES visitor_management_schema.user_table (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
